# --- This file was generated by Sybase Installer ---
#
sybinit.release_directory: /opt/sybase
sybinit.product: sqlsrv
sqlsrv.server_name: MYSYBASE
sqlsrv.sa_password: myPassword
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: localhost
sqlsrv.network_port_list: 5000
sqlsrv.application_type: MIXED
sqlsrv.server_page_size: 8k
sqlsrv.force_buildmaster: no
sqlsrv.addl_cmdline_parameters:
sqlsrv.master_device_physical_name: /opt/sybase/data/master.dat
sqlsrv.master_device_size: 384
sqlsrv.master_database_size: 300
sqlsrv.errorlog: /opt/sybase/ASE-16_0/install/MYSYBASE.log
sqlsrv.sort_order:	bin_utf8
sqlsrv.default_characterset:	utf8
sqlsrv.default_language:	us_english
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: /opt/sybase/data/sysprocs.dat
sqlsrv.sybsystemprocs_device_size: 184
sqlsrv.sybsystemprocs_database_size: 184
sqlsrv.sybsystemdb_device_physical_name: /opt/sybase/data/sybsysdb.dat
sqlsrv.sybsystemdb_device_size: 24
sqlsrv.sybsystemdb_database_size: 24
sqlsrv.tempdb_device_physical_name: /opt/sybase/data/tempdbdev.dat
sqlsrv.tempdb_device_size: 325
sqlsrv.tempdb_database_size: 325
sqlsrv.default_backup_server: MYSYBASE_BS
sqlsrv.do_configure_pci: yes
sqlsrv.sybpcidb_device_physical_name: /opt/sybase/data/sybpcidbdev_data.dat
sqlsrv.sybpcidb_device_size: 384
sqlsrv.sybpcidb_database_size: 384
sqlsrv.do_optimize_config: no
sqlsrv.avail_physical_memory:
sqlsrv.avail_cpu_num:

